### ISSUE TITLE
Rules for keeping data in sync

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#11]
- [ ] Current user profile
- [ ] Current user's campaign activity
- [ ] Public user profile
- [ ] Public user campaign activity
- [ ] Campaign details
- [ ] User Reportback Items
- [ ] Group Reportback Items
- [ ] Public gallery Reportback Items
- [ ] Push notifications

**Comment by jonuy** [comment]
Things talked about during our meeting:
- User profile: sync with API each time user goes to the Hub/Profile screen. Save data locally to make available offline.
- User activities: same as above
- Campaign details: sync with API ... rarely? once a month? But does save locally so that content is at least viewable offline.
- Group and public gallery reportback items will not be saved locally for offline viewing

**Comment by aaronschachter** [comment]
v1 will not store anything offline, so no need for sync.
